name: upper-build

on: 
    push: 
        paths: 
            - ".github/workflows/upper-build.yml"
            - "./upper"
            
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        name: go-build
        steps:
            - run: go version