name: upper-capture
on:
  push:
    paths:
      - ".github/workflows/upper-cross.yml"
      - "./upper"

  workflow_dispatch:

jobs:
  build-cross-platform:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum

      - run: chmod +x ./build.xplat.sh
      - run: ./build.xplat.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: ./upper/bin/upper*
          tag_name: ${{ github.ref_name }}
          body: "Binaries for upper (go) command line tool. "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref_name, 'refs/tags/')
