name: upper-capture
on:
  push:
    paths:
      - ".github/workflows/upper-capture.yml"
      - "./upper"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          name: go-build-output
          path: ./upper/upper
